var positive_shape = 'triangle'
var negative_shape = 'square'
var neutral_shape_1 = 'circle'
var neutral_shape_2 = 'star'

var training_phase_trials = [
  {shape: 'circle', word_type: 'positive', word: 'LUCKY'},
  {shape: 'star', word_type: 'negative', word: 'DISTRESSED'},
  {shape: 'circle', word_type: 'positive', word: 'RESCUE'},
  {shape: 'star', word_type: 'positive', word: 'HOPEFUL'},
  {shape: 'triangle', word_type: 'positive', word: 'COMFORT'},
  {shape: 'triangle', word_type: 'negative', word: 'ANXIOUS'},
  {shape: 'triangle', word_type: 'positive', word: 'TERRIFIC'},
  {shape: 'star', word_type: 'positive', word: 'FLOWER'},
  {shape: 'triangle', word_type: 'positive', word: 'GOOD'},
  {shape: 'circle', word_type: 'negative', word: 'WASTE'},
  {shape: 'star', word_type: 'negative', word: 'BURIAL'},
  {shape: 'circle', word_type: 'positive', word: 'KINDNESS'},
  {shape: 'circle', word_type: 'positive', word: 'SAFE'},
  {shape: 'star', word_type: 'positive', word: 'IMPROVE'},
  {shape: 'square', word_type: 'positive', word: 'PROTECTED'},
  {shape: 'star', word_type: 'negative', word: 'INFECTION'},
  {shape: 'square', word_type: 'negative', word: 'FATIGUED'},
  {shape: 'triangle', word_type: 'positive', word: 'ACHIEVEMENT'},
  {shape: 'triangle', word_type: 'positive', word: 'BRAVE'},
  {shape: 'circle', word_type: 'negative', word: 'SEVERE'},
  {shape: 'triangle', word_type: 'negative', word: 'GRIEF'},
  {shape: 'square', word_type: 'negative', word: 'AMBULANCE'},
  {shape: 'star', word_type: 'positive', word: 'HUG'},
  {shape: 'star', word_type: 'negative', word: 'PRESSURE'},
  {shape: 'triangle', word_type: 'positive', word: 'LIVELY'},
  {shape: 'triangle', word_type: 'negative', word: 'SICK'},
  {shape: 'square', word_type: 'negative', word: 'NIGHTMARE'},
  {shape: 'triangle', word_type: 'positive', word: 'OPTIMISM'},
  {shape: 'star', word_type: 'negative', word: 'OVERWHELMED'},
  {shape: 'star', word_type: 'positive', word: 'ACCEPTANCE'},
  {shape: 'circle', word_type: 'negative', word: 'FEVER'},
  {shape: 'star', word_type: 'negative', word: 'HELPLESS'},
  {shape: 'circle', word_type: 'positive', word: 'DREAM'},
  {shape: 'circle', word_type: 'positive', word: 'CAREFREE'},
  {shape: 'square', word_type: 'negative', word: 'DESPAIRING'},
  {shape: 'circle', word_type: 'negative', word: 'UNHAPPY'},
  {shape: 'square', word_type: 'negative', word: 'GERMS'},
  {shape: 'square', word_type: 'negative', word: 'OUTRAGE'},
  {shape: 'circle', word_type: 'negative', word: 'DEPRESSED'},
  {shape: 'triangle', word_type: 'positive', word: 'FREEDOM'},
  {shape: 'square', word_type: 'negative', word: 'TRAUMA'},
  {shape: 'circle', word_type: 'positive', word: 'BEAUTIFUL'},
  {shape: 'star', word_type: 'positive', word: 'RELAXED'},
  {shape: 'circle', word_type: 'positive', word: 'FAMILY'},
  {shape: 'square', word_type: 'negative', word: 'DISCOURAGED'},
  {shape: 'star', word_type: 'negative', word: 'SCARED'},
  {shape: 'triangle', word_type: 'negative', word: 'MUCUS'},
  {shape: 'square', word_type: 'negative', word: 'VICTIM'},
  {shape: 'star', word_type: 'positive', word: 'EASYGOING'},
  {shape: 'star', word_type: 'negative', word: 'LONELINESS'},
  {shape: 'circle', word_type: 'negative', word: 'SUFFOCATE'},
  {shape: 'square', word_type: 'negative', word: 'ROUGH'},
  {shape: 'square', word_type: 'positive', word: 'CHEER'},
  {shape: 'triangle', word_type: 'positive', word: 'LEISURELY'},
  {shape: 'square', word_type: 'negative', word: 'WOUNDS'},
  {shape: 'circle', word_type: 'negative', word: 'INSECURE'},
  {shape: 'triangle', word_type: 'positive', word: 'MIRACLE'},
  {shape: 'circle', word_type: 'positive', word: 'CONFIDENT'},
  {shape: 'square', word_type: 'positive', word: 'TRIUMPHANT'},
  {shape: 'circle', word_type: 'positive', word: 'REWARD'},
  {shape: 'star', word_type: 'positive', word: 'GRATEFUL'},
  {shape: 'triangle', word_type: 'positive', word: 'LAUGHTER'},
  {shape: 'square', word_type: 'positive', word: 'FUN'},
  {shape: 'triangle', word_type: 'positive', word: 'PROGRESS'},
  {shape: 'triangle', word_type: 'positive', word: 'THOUGHTFUL'},
  {shape: 'square', word_type: 'negative', word: 'DEATH'},
  {shape: 'circle', word_type: 'negative', word: 'STRESS'},
  {shape: 'square', word_type: 'negative', word: 'TRAGEDY'},
  {shape: 'star', word_type: 'negative', word: 'USELESS'},
  {shape: 'square', word_type: 'negative', word: 'PANIC'},
  {shape: 'circle', word_type: 'negative', word: 'ANGUISHED'},
  {shape: 'triangle', word_type: 'positive', word: 'RAINBOW'},
  {shape: 'square', word_type: 'negative', word: 'HOSPITAL'},
  {shape: 'star', word_type: 'negative', word: 'BROKEN'},
  {shape: 'circle', word_type: 'negative', word: 'CHAOS'},
  {shape: 'triangle', word_type: 'positive', word: 'JOY'},
  {shape: 'square', word_type: 'negative', word: 'ANGRY'},
  {shape: 'triangle', word_type: 'positive', word: 'SOCIAL'},
  {shape: 'star', word_type: 'positive', word: 'VICTORY'},
  {shape: 'star', word_type: 'positive', word: 'SOOTHE'}
]

